{{- if .Values.argoCD.enabled }}
{{- range $name, $spec := .Values.argoCD.applications.specs }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ printf "%s-%s" $.Release.Name $name }}'
  namespace: {{ $.Values.argoCD.appNamespace | default $.Values.argoCD.namespace }}
{{- with merge ($spec.annotations | default dict) $.Values.argoCD.applications.annotations}}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- if not (and ( hasKey $spec "finalizers" ) (not $spec.finalizers )) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
{{- end}}
spec:
  destination:
    namespace: {{ $spec.namespace | default $name}}
    server: {{ include "k3s.apiUrl" $ }}
  project: {{ include "k3s.argocdProject" $ }}
  source:
{{- with $spec.path }}
    path: {{ . }}
{{- end }}
{{- with $spec.chart }}
    chart: {{ . }}
{{- end }}
    repoURL: {{ $spec.repoUrl | default $.Values.argoCD.applications.repoUrl }}
    targetRevision: {{ $spec.targetRevision | default $.Values.argoCD.applications.targetRevision }}
{{- $hosts := list }}
{{- range $.Values.service.domains }}
{{- $hosts = append $hosts (printf "%s.%s.%s" $name (include "k3s.hostname" $ ) . ) }}
{{- end }}
{{- $values := $spec.values }}
{{- if $spec.injectHost }}
{{- $values = merge (default $spec.values dict) (dict "ingress" (dict "hosts" $hosts)) }}
{{- end }}
    helm:
      releaseName: {{ $name }}
      valuesObject:
{{- ( tpl (toYaml $values ) $ )  | nindent 8 }}
{{- with $spec.valueFiles }}
      valueFiles:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with $spec.syncPolicy | default $.Values.argoCD.applications.syncPolicy}}
  syncPolicy:
{{- toYaml . | nindent 4 }}
{{- end }}
---
{{- end }}
{{- end }}