{{- if .Values.argoCD.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k3s.fullname" . }}
  namespace: {{ .Values.argoCD.namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- .Values.argoCD.cluster.labels | toYaml | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  name: {{ include "k3s.fullname" . | b64enc }}
  server: {{ include "k3s.apiUrl" . | b64enc }}
  project: {{ include "k3s.argocdProject" . | b64enc }}
type: Opaque
{{- end }}