{{- if .Values.service.ingressRouteTCP }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "k3s.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`{{ include "k3s.apiHostExternal" . }}`)
      services:
        - name: {{ include "k3s.fullname" . }}
          port: 443
  tls:
    passthrough: true
{{- end }}