apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-server
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  {{ .Values.storage.storageClassNameK3s | default .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size.server }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-kubeconfig
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size.config }}

---
{{- if and .Values.postgresql.enabled .Values.postgresql.primary.persistence.enabled .Values.postgresql.primary.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.primary.persistence.existingClaim }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  {{ .Values.postgresql.primary.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size | quote }}
{{- end }}