{{- if .Values.argoCD.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ default (include "k3s.fullname" .) .Values.serviceAccount.roleName }}
  namespace: {{ .Values.argoCD.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "k3s.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ default (include "k3s.fullname" .) .Values.serviceAccount.roleName }}
{{- end }}