apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s.fullname" . }}
  labels:
    {{- include "k3s.labels" . | nindent 4 }}
  annotations:
    {{- include "k3s.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: 6443
      targetPort: api
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "k3s.selectorLabels" . | nindent 4 }}
