apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meetup
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
  sourceNamespaces:
    - meetup
    - argocd
  description: Meetup project
  destinations:
    - namespace: 'meetup*'
      server: 'https://kubernetes.default.svc'
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
