apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meetup-k3s-root-ca
  namespace: cert-manager
spec:
  commonName: Meetup K3s CA
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: meetup-k3s-root-ca-secret
  subject:
    countries:
      - NL
    localities:
      - Eindhoven
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: meetup-k3s-root-ca
spec:
  ca:
    secretName: meetup-k3s-root-ca-secret