apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: meetup-k3s
  namespace: argocd
spec:
  destination:
    namespace: meetup
    server: https://kubernetes.default.svc
  project: meetup
  source:
    path: applications/k3s
    repoURL: https://github.com/koen-de-laat/devops-meetup
    targetRevision: HEAD
    helm:
      valuesObject:
        argoCD:
          applications:
            targetRevisions: $ARGOCD_APP_SOURCE_TARGET_REVISION
          appNamespace: meetup
          cluster:
            labels:
              skip-default-apps: "true"
        storage:
          storageClassNameK3s: local-path
        service:
          type: ClusterIP
          domains:
            - koendelaat.nl
          ingressRouteTCP: true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
       - /data/config
      namespace: argocd
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
